### ISSUE TITLE
Problem trimming the video

### ISSUE THREAD

**Issue by giggioman00** [TypesettingTools/Aegisub-Motion#34]
If I trim a line using x264, the output video is not what I chosen as start and as end in the subs.
This script trim a completely different part of the video.

**Comment by torque** [comment]
It's impossible for me to determine what the issue is here without more information. My first question would be, what format is the video file? x264 uses FFMS2 to decode the input video, which I think has issues seeking properly with certain input formats, such as TS (this includes blu-ray M2TS).

If that's the case, I would recommend remuxing to mkv and trying again. If that's not the case, I'm not really sure how to proceed since nobody else has ever mentioned a problem like this.

**Comment by giggioman00** [comment]
Hi, the decoder was the problem. 
I replaced my old x264.exe with the latest version and now works well.

**Comment by torque** [comment]
Ok.
